version: "3.8"
services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./Config/nginx.conf:/etc/nginx/nginx.conf
            - ./data/certbot/conf:/etc/letsencrypt 
            - ./data/certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt 
            - ./data/certbot/www:/var/www/certbot
    db:
        image: mysql:8.2
        container_name: mysql-db
        build:
            context: ./Config/Database
            dockerfile: Dockerfile        
        restart:
            always
        ports:
            - "3306:3306"
    redis:
        image: redis
        container_name: redis
        restart:
            always
        ports:
            - "6379:6379"
    api_game_server:
        container_name: api_game_server
        ports:
            - "5000:80"
        build:
            context: ./API_Game_server
        restart:
            always
        depends_on:
            - db
            - redis
    api_auth_server:
        container_name: api_auth_server
        ports:
            - "5001:80"            
        build:
            context: ./Auth_Server
            dockerfile: Dockerfile
        restart:
            always
        depends_on:
            - db
            - redis

